version: "3.7"

services:

  certbot:
    build:
      context: docker/mkcert
    image: mkcert
    volumes:
      - ./docker/certbot/conf:/root/certs
      - ${CAROOT:-.}:/root/caroot

  bitcoind:
    expose:
      - 18444

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-dev

    expose:
      - 3000

    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-invalid}
