version: "3.7"

services:

  certbot:
    image: certbot/certbot
    # crazy bash-isms explained:
    # check if certificate is up for renewal every 12 hours,
    # as recommended by Let's Encrypt
    # prettier-ignore
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      BITCOIN_NETWORK: ${BITCOIN_NETWORK:-regtest}
      API_URL: https://api.${SERVER_NAME:-localhost}

  bitcoind:
    expose:
      - 8332
